---
title: "Cu sediment toxicity"
author: "Dave Costello"
date: "August 4, 2015"
output: html_document
---

```{r Functions, include=F}
#Function to calculation EC values for growth with 95% confidence intervals
ECXX=function(model,percent){
  ECname = paste("EC",percent)
  dose=names(model$dataClasses)
  EC = (100-percent)/100 
  ref = model$m$getPar()[1]
  min.x = 1
  max.x = 10000 #Might need to change the range
  range = seq(min.x,max.x,by=1)
  new.range = data.frame(frame=seq(min.x,max.x,by=1))
  names(new.range)[[1]]=dose
  bf = predict(model,newdata=new.range)
  locEC=which.min(abs(bf-ref*EC))
  se = sqrt(apply(attr(predict(model, newdata=new.range),"gradient"),1,function(x) sum(vcov(model)*outer(x,x))))
  LCI=bf+se*qnorm(0.025)
  locL=which.min(abs(LCI-ref*EC))
  UCI=bf+se*qnorm(0.975)
  locU=which.min(abs(UCI-ref*EC))
  result=c(range[locEC],range[locL],range[locU])
  result = signif(result,digits=3)
  names(result)[[1]]=ECname
  names(result)[[2]]="Lower-bound (2.5%)"
  names(result)[[3]]="Upper-bound (97.5%)"
  print(result)
  mat=cbind(new.range,bf,LCI,UCI)
  invisible(list(ResultTable=result,CImat=mat))
}

#Function to calculation LC values for survival with 95% confidence intervals
LCXX=function(model,percent){
  LCname = paste("LC",percent)
  dose = names(model$coef)[2]
  dose = ifelse(grepl("log",dose),sub("\\).*", "", sub(".*\\(", "", dose)) ,dose)
  EC = (100-percent)/100 
  min.x = 1
  max.x = 10000 #Might need to change the range
  range = seq(min.x,max.x,by=1)
  new.range = data.frame(frame=seq(min.x,max.x,by=1))
  names(new.range)[[1]]=dose
  bf = predict(model,newdata=new.range,type="response",se.fit=T)
  locLC=which.min(abs(bf$fit-EC))
  LCI=bf$fit+bf$se.fit*qnorm(0.025)
  locL=which.min(abs(LCI-EC))
  UCI=bf$fit+bf$se.fit*qnorm(0.975)
  locU=which.min(abs(UCI-EC))
  result=c(range[locLC],range[locL],range[locU])
  result = signif(result,digits=3)
  names(result)[[1]]=LCname
  names(result)[[2]]="Lower-bound (2.5%)"
  names(result)[[3]]="Upper-bound (97.5%)"
  print(result)
  mat=cbind(new.range,bf$fit,LCI,UCI)
  invisible(list(ResultTable=result,CImat=mat))
  	}

#Function to complete ANOVA-like inference from non-linear least-squares regression
ANOVA_F=function(mod,y){
  ypred=predict(mod)
  y.no.na = y[!is.na(y)]
  dfnum = length(mod$m$getPar())-1
  dfden = length(y.no.na)-length(mod$m$getPar())
  SSerr=sum((ypred-y.no.na)^2)
	SSreg=sum((ypred-mean(y.no.na))^2)
	SStot = SSerr + SSreg
  Frat = (SSreg/dfnum)/(SSerr/dfden)
  probF = pf(Frat,dfnum,dfden,lower.tail=F)
  Rsquare = 1-(SSerr/SStot)
  result=c(Frat,probF,Rsquare)
  names(result)[[1]]="F ratio"
	names(result)[[2]]="P-value"
  names(result)[[3]]="R-squared"
  return(result)
	}
```

```{r Import data, include=F}
CuTox<-read.csv(file="Cu_Ha.csv")
summary(CuTox)
CuTox$Nom_Cu<-factor(CuTox$Nom_Cu)
CuTox$Dead<-10-CuTox$Count

OcoeeTox<-subset(CuTox,CuTox$Sediment=="Ocoee")
DowTox<-subset(CuTox,CuTox$Sediment=="Dow")
OcoeeTox$Nom_Cu<-OcoeeTox$Nom_Cu[,drop=T]
DowTox$Nom_Cu<-DowTox$Nom_Cu[,drop=T]
DowToxF<-subset(DowTox,DowTox$Treat=="F")
DowToxS<-subset(DowTox,DowTox$Treat=="S")
OcoeeToxF<-subset(OcoeeTox,OcoeeTox$Treat=="F")
OcoeeToxS<-subset(OcoeeTox,OcoeeTox$Treat=="S")
```

###Dow flume-aged - EC10 and LC50
```{r Dow flume-aged, echo=F}
plot(Count/10~(TOT_Cu),data=DowToxF,log="x")
DFsurv <- glm(cbind(Count,Dead)~log10(TOT_Cu),data=DowToxF,family=binomial)
summary(DFsurv)
shapiro.test(resid(DFsurv)) #OK
#p < 0.001
1-DFsurv$deviance/DFsurv$null.deviance
#R2 = 0.55

DFs = LCXX(DFsurv,50) #LC50 = 435 mg/kg
for(i in 1:3){lines(DFs$CImat[,1],(DFs$CImat[,1+i]))}

plot(RGR~TOT_Cu,data=DowToxF,log="x")
DFg <- nls(RGR~SSlogis(log10(TOT_Cu),Asym,xmid,scal),data=DowToxF)
summary(DFg)
shapiro.test(resid(DFg)) #OK
ANOVA_F(DFg,DowToxF$RGR) # p < 0.001, r2 = 0.88

DF = ECXX(DFg,10) #EC10 = 57
for(i in 1:3){lines(DF$CImat[,1],DF$CImat[,1+i])}
```

###Dow spiked - EC10 and LC50
```{r Dow spiked, echo=F}
plot(Count/10~TOT_Cu,data=DowToxS,log="x")
DSsurv <- glm(cbind(Count,Dead)~log10(TOT_Cu),data=DowToxS,family=binomial)
summary(DSsurv)
shapiro.test(resid(DSsurv)) #0.003
1-DSsurv$deviance/DSsurv$null.deviance
#p < 0.001, r2 = 0.74

DSs = LCXX(DSsurv,50) #LC50 395 
for(i in 1:3){lines(DSs$CImat[,1],DSs$CImat[,i+1])}

plot(RGR~TOT_Cu,data=DowToxS,log="x")
DSg <- nls(RGR~SSlogis(log10(TOT_Cu),Asym,xmid,scal),data=DowToxS)
summary(DSg)
shapiro.test(resid(DSg)) #OK
ANOVA_F(DSg,DowToxS$RGR) #p < 0.001, r2 = 0.93

DS = ECXX(DSg,10) #EC10 = 29
for(i in 1:3){lines(DS$CImat[,1],DS$CImat[,1+i])}
```

###Bioavailable Cu and growth response
```{r Cu bioavail, echo=F}
#Dow
plot(RGR~SEMAVSfOC2,data=DowToxS,ylim=c(0,0.12),col="orangered3",las=1,log="x",xlim=c(1,1000))
points(RGR~SEMAVSfOC2,data=DowToxF,col="royalblue3",pch=15)

#Dow F alone
DFsao <- nls(RGR~SSlogis(log10(SEMAVSfOC2),Asym,xmid,scal),data=DowToxF)
shapiro.test(resid(DFsao))
summary(DFsao)
ANOVA_F(DFsao,DowToxF$RGR)
DF.EC <- ECXX(DFsao,10)

#Dow S alone
DSsao <- nls(RGR~SSlogis(log10(SEMAVSfOC2),Asym,xmid,scal),data=DowToxS)
shapiro.test(resid(DSsao))
summary(DSsao)
ANOVA_F(DSsao,DowToxS$RGR)
DS.EC <-ECXX(DSsao,10)

#Combined model
Dsao <- nls(RGR~SSlogis(log10(SEMAVSfOC2),Asym,xmid,scal),data=DowTox)
shapiro.test(resid(Dsao))
summary(Dsao)
ANOVA_F(Dsao,DowTox$RGR)
D.EC <- ECXX(Dsao,10)

#Ocoee
plot(RGR~SEMAVSfOC2,data=OcoeeToxS,ylim=c(0,0.12),col="orangered3",las=1,log="x",xlim=c(1,10000))
points(RGR~SEMAVSfOC2,data=OcoeeToxF,col="royalblue3",pch=15)

#Ocoee F alone
OFsao <- nls(RGR~SSlogis(log10(SEMAVSfOC2),Asym,xmid,scal),data=OcoeeToxF)
summary(OFsao)
shapiro.test(resid(OFsao))
ANOVA_F(OFsao,OcoeeToxF$RGR)
OF.EC <- ECXX(OFsao,10)

#Ocoee S alone
OSsao <- nls(RGR~SSlogis(log10(SEMAVSfOC2),Asym,xmid,scal),data=OcoeeToxS)
summary(OSsao)
shapiro.test(resid(OSsao))
ANOVA_F(OSsao,OcoeeToxS$RGR)
OS.EC <- ECXX(OSsao,10)

#Combined model
Osao <- nls(RGR~SSlogis(log10(SEMAVSfOC2),Asym,xmid,scal),data=OcoeeTox)
shapiro.test(resid(Osao))
summary(Osao)
ANOVA_F(Osao,OcoeeTox$RGR)
O.EC <- ECXX(Osao,10)
```
